backend:
  name: git-gateway
  branch: master
  repo: ogdendavis/saratogaspringsdoodles

media_folder: static/img
public_folder: /img

collections:
  - name: 'dogs'
    label: 'Dogs'
    label_singular: 'Dog'
    folder: 'src/cms/dogs'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Breed', name: 'breed', widget: 'string' }
      - { label: 'Color', name: 'color', widget: 'string' }
      - {
          label: 'Birthdate',
          name: 'birthdate',
          widget: 'datetime',
          timeFormat: false,
        }
      - {
          label: 'Gender',
          name: 'gender',
          widget: 'select',
          options:
            [{ label: 'Male', value: 'm' }, { label: 'Female', value: 'f' }],
        }
      - { label: 'Bio', name: 'body', widget: 'markdown' }
  - name: 'litters'
    label: 'Litters'
    label_singular: 'Litter'
    folder: 'src/cms/litters'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Title',
          name: 'title',
          widget: 'string',
          comment: 'Litters should have a unique identifying title',
        }
      - label: 'Sire'
        name: 'sire'
        widget: 'object'
        fields:
          - { label: 'Name', name: 'sire_name', widget: 'string' }
          - {
              label: 'In house?',
              name: 'sire_in_house',
              widget: 'boolean',
              required: false,
            }
          - {
              label: 'Photo',
              name: 'sire_image',
              widget: 'image',
              required: false,
            }
      - label: 'Dam'
        name: 'dam'
        widget: 'object'
        fields:
          - { label: 'Name', name: 'dam_name', widget: 'string' }
          - {
              label: 'In house?',
              name: 'dam_in_house',
              widget: 'boolean',
              required: false,
            }
          - {
              label: 'Photo',
              name: 'dam_image',
              widget: 'image',
              required: false,
            }
      - {
          label: 'Count',
          name: 'count',
          widget: 'number',
          required: false,
          default: 0,
        }
      - label: 'Size Range'
        name: 'size'
        widget: 'object'
        fields:
          - {
              label: 'Min',
              name: 'min',
              widget: 'number',
              required: false,
              default: 0,
            }
          - {
              label: 'Max',
              name: 'max',
              widget: 'number',
              required: false,
              default: 0,
            }
      - {
          label: 'Colors',
          name: 'colors',
          widget: 'string',
          required: false,
          default: '',
        }
      - {
          label: 'Expected Date',
          name: 'date',
          widget: 'datetime',
          timeFormat: false,
          required: false,
        }
      - { label: 'Info', name: 'body', widget: 'markdown', required: false }
  - name: 'site_copy'
    label: 'General Info'
    media_folder: 'img'
    files:
      - name: 'about_breeder'
        label: 'About You'
        file: 'src/cms/general/breeder.md'
        fields:
          - { label: 'Your Name', name: 'title', widget: 'string' }
          - {
              label: 'Photo',
              name: 'breeder_photo',
              widget: 'image',
              required: false,
            }
          - { label: 'Your Bio', name: 'body', widget: 'markdown' }
      - name: 'about_business'
        label: 'About Your Business'
        file: 'src/cms/general/business.md'
        fields:
          - { label: 'Business Name', name: 'title', widget: 'string' }
          - {
              label: 'Logo',
              name: 'business_logo',
              widget: 'image',
              required: false,
            }
          - {
              label: 'Photo',
              name: 'business_photo',
              widget: 'image',
              required: false,
            }
          - { label: 'About Your Business', name: 'body', widget: 'markdown' }
      - name: 'about_dogs'
        label: 'About Your Sires & Dams'
        file: 'src/cms/general/dogs.md'
        fields:
          - {
              label: 'General Info on Sires & Dams',
              name: 'body',
              widget: 'markdown',
            }
      - name: 'about_testing'
        label: 'Genetic Testing'
        file: 'src/cms/general/testing.md'
        fields:
          - {
              label: 'Info on Genetic Testing',
              name: 'body',
              widget: 'markdown',
            }
      - name: 'about_litters'
        label: 'About Your Litters'
        file: 'src/cms/general/litters.md'
        fields:
          - {
              label: 'General Info on Litters',
              name: 'body',
              widget: 'markdown',
            }
      - name: 'about_puppy_training'
        label: 'About ENS / Puppy culture'
        file: 'src/cms/general/puppy-training.md'
        fields:
          - {
              label: 'Info on ENS & Puppy Culture',
              name: 'body',
              widget: 'markdown',
            }
      - name: 'about_welcome'
        label: 'Welcome messages'
        file: 'src/cms/general/welcome.md'
        fields:
          - {
              label: 'Welcome to the website',
              name: 'body',
              widget: 'markdown',
            }
          - {
              label: 'Nutrition Intro',
              name: 'welcome_nutrition',
              widget: 'markdown',
            }
          - {
              label: 'Training Intro',
              name: 'welcome_training',
              widget: 'markdown',
            }
          - {
              label: 'Enrichment Intro',
              name: 'welcome_enrichment',
              widget: 'markdown',
            }
          - {
              label: 'Contact us text (1 paragraph)',
              name: 'welcome_contact',
              widget: 'text',
            }
      - name: 'about_policies'
        label: 'Policies & Pricing'
        file: 'src/cms/general/policies.md'
        fields:
          - {
              label: 'Info on Policies & Pricing',
              name: 'body',
              widget: 'markdown',
            }
      - name: 'about_guardians'
        label: 'Guardian Program'
        file: 'src/cms/general/guardians.md'
        fields:
          - {
              label: 'Info on Guardian Program',
              name: 'body',
              widget: 'markdown',
            }
      - name: 'about_contact'
        label: 'Contact Info'
        file: 'src/cms/general/contact.md'
        fields:
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - label: 'Social Media'
            name: 'social'
            widget: 'object'
            fields:
              - {
                  label: 'Facebook Profile',
                  name: 'facebook',
                  widget: 'string',
                  required: false,
                }
              - {
                  label: 'Instagram Profile',
                  name: 'instagram',
                  widget: 'string',
                  required: false,
                }
              - {
                  label: 'Twitter Profile',
                  name: 'twitter',
                  widget: 'string',
                  required: false,
                }
              - {
                  label: 'Good Dog Profile',
                  name: 'gooddog',
                  widget: 'string',
                  required: false,
                }
          - label: 'Address'
            name: 'address'
            widget: 'object'
            fields:
              - {
                  label: 'Street',
                  name: 'street',
                  widget: 'string',
                  required: false,
                }
              - {
                  label: 'City',
                  name: 'city',
                  widget: 'string',
                  required: false,
                }
              - {
                  label: 'State',
                  name: 'state',
                  widget: 'string',
                  required: false,
                }
              - {
                  label: 'Zip Code',
                  name: 'zip',
                  widget: 'string',
                  required: false,
                }
  - name: 'gallery'
    label: 'Photo Gallery'
    label_singular: 'Image'
    folder: 'src/cms/gallery'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
  - name: 'products'
    label: 'Products'
    label_singular: 'Product'
    folder: 'src/cms/products'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Section',
          name: 'section',
          widget: 'select',
          multiple: true,
          options:
            [
              { label: 'Nutrition', value: 'nutrition' },
              { label: 'Training', value: 'training' },
              { label: 'Enrichment', value: 'enrichment' },
            ],
        }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Link', name: 'link', widget: 'string' }
