backend:
  name: git-gateway
  branch: master
  repo: ogdendavis/midwoofery-1

media_folder: static/img
public_folder: /img

collections:
  - name: 'dogs'
    label: 'Dogs'
    label_singular: 'Dog'
    folder: 'src/cms/dogs'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Breed', name: 'breed', widget: 'string' }
      - { label: 'Color', name: 'color', widget: 'string' }
      - {
          label: 'Birthdate',
          name: 'birthdate',
          widget: 'datetime',
          timeFormat: false,
        }
      - {
          label: 'Gender',
          name: 'gender',
          widget: 'select',
          options:
            [{ label: 'Male', value: 'm' }, { label: 'Female', value: 'f' }],
        }
      - { label: 'Bio', name: 'bio', widget: 'text' }
  - name: 'litters'
    label: 'Litters'
    label_singular: 'Litter'
    folder: 'src/cms/litters'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Title',
          name: 'title',
          widget: 'string',
          comment: 'Litters should have a unique identifying title',
        }
      - label: 'Sire'
        name: 'sire'
        widget: 'object'
        fields:
          - { label: 'Name', name: 'sire_name', widget: 'string' }
          - {
              label: 'In house?',
              name: 'sire_in_house',
              widget: 'boolean',
              required: false,
            }
          - {
              label: 'Photo',
              name: 'sire_image',
              widget: 'image',
              required: false,
            }
      - label: 'Dam'
        name: 'dam'
        widget: 'object'
        fields:
          - { label: 'Name', name: 'dam_name', widget: 'string' }
          - {
              label: 'In house?',
              name: 'dam_in_house',
              widget: 'boolean',
              required: false,
            }
          - {
              label: 'Photo',
              name: 'dam_image',
              widget: 'image',
              required: false,
            }
      - { label: 'Count', name: 'count', widget: 'number', required: false }
      - label: 'Size Range'
        name: 'size'
        widget: 'object'
        fields:
          - { label: 'Min', name: 'min', widget: 'number', required: false }
          - { label: 'Max', name: 'max', widget: 'number', required: false }
      - { label: 'Colors', name: 'colors', widget: 'string', required: false }
      - {
          label: 'Expected Date',
          name: 'date',
          widget: 'datetime',
          timeFormat: false,
          required: false,
        }
